[colors.primary]
background = "#000000"
foreground = "#d4d7ff"

[colors.normal]
black   = "#222236"
red     = "#d95177"
green   = "#78dca7"
yellow  = "#fcf39c"
blue    = "#759eea"
magenta = "#8783d9"
cyan    = "#6be5e3"
white   = "#e4e7ff"

[colors.bright]
black   = "#29293f"
red     = "#d54c73"
green   = "#7bdba6"
yellow  = "#fcf295"
blue    = "#6d98e8"
magenta = "#837dd7"
cyan    = "#65dedc"
white   = "#f4f7ff"

[colors.dim]
black   = "#12121f"
red     = "#df4e75"
green   = "#84e5ac"
yellow  = "#fcf4a2"
blue    = "#7ea4ec"
magenta = "#908cdb"
cyan    = "#72e7e5"
white   = "#d4d7ff"

